// <auto-generated />
using System;
using EngineeringPerformance.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EngineeringPerformance.Infrastructure.Migrations
{
    [DbContext(typeof(PerformanceDbContext))]
    [Migration("20260806041151_DecimalExpectedFilledDays")]
    partial class DecimalExpectedFilledDays
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("EngineeringPerformance.Domain.AnalysisExclusion", b =>
                {
                    b.Property<string>("EmployeeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeName");

                    b.ToTable("analysis_exclusion", (string)null);
                });

            modelBuilder.Entity("EngineeringPerformance.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConsultant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNonBillable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnProbationFromRoster")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsOnProbation");

                    b.Property<bool>("IsUpdownFromRoster")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ProbationOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeniorityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("UpdownOverride")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("employee", (string)null);
                });

            modelBuilder.Entity("EngineeringPerformance.Domain.EmployeeMonthlyPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ApprovalScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ApprovedHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AttendanceDays")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AttendanceDisciplineScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AttendanceTimesheetHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BillableHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ComplianceHours")
                        .HasColumnType("TEXT");

                    b.Property<int>("DetailedEntries")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DetailedHours")
                        .HasColumnType("TEXT");

                    b.Property<int>("EarlyDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EnteredHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedTimesheetDays")
                        .HasColumnType("TEXT");

                    b.Property<int>("LateDays")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LeaveDays")
                        .HasColumnType("TEXT");

                    b.Property<int>("LessDurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingPunchDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NonBillableHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OfficeHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OperationalScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PunchHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TimesheetCompletionScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TimesheetFilledDays")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TrainingHours")
                        .HasColumnType("TEXT");

                    b.Property<int>("UniqueProjects")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month", "EmployeeName")
                        .IsUnique();

                    b.ToTable("employee_monthly_performance", (string)null);
                });

            modelBuilder.Entity("EngineeringPerformance.Domain.ImportAuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReplacedExisting")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReportType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportedUtc");

                    b.ToTable("import_audit_entry", (string)null);
                });

            modelBuilder.Entity("EngineeringPerformance.Domain.ImportedSourceFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SheetCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month", "ReportType")
                        .IsUnique();

                    b.ToTable("imported_source_file", (string)null);
                });

            modelBuilder.Entity("EngineeringPerformance.Domain.PeerReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Collaboration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Communication")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Reliability")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TechnicalHelp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month", "ReviewerCode", "SubjectCode")
                        .IsUnique();

                    b.ToTable("peer_review", (string)null);
                });

            modelBuilder.Entity("EngineeringPerformance.Domain.ReportingMonth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("reporting_month", (string)null);
                });

            modelBuilder.Entity("EngineeringPerformance.Domain.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("team", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
